#!/bin/zsh

# NOTE: See (or create) .ampy

source .ampy

cd work-quality-monitor

# ------------------------------------------------
# ------------------------------------------------
# ------------------------------------------------
function _put_all_files() {
  for file in *.py; do
    echo "Putting $file..."
    pipenv run ampy put $file
  done

  echo "Resetting..."
  pipenv run ampy reset
  echo "Done."
}

function _start_repl() {
  python -m serial.tools.miniterm --raw $AMPY_PORT $AMPY_BAUD
}

# ------------------------------------------------
# ------------------------------------------------
# ------------------------------------------------
if [[ $# == 0 ]] ; then
  _put_all_files
  _start_repl
  exit
fi

case $1 in
  repl)
    _start_repl
    ;;
  *)
    pipenv run ampy $@
    ;;
esac


