#!/bin/zsh

# NOTE: See (or create) .ampy

cd work-quality-monitor

# ------------------------------------------------
# ------------------------------------------------
# ------------------------------------------------
function _put_all_files() {
  for file in *.py; do
    echo "Putting $file..."
    pipenv run ampy put $file
  done

  echo "Resetting..."
  pipenv run ampy reset
  echo "Done."
}

# ------------------------------------------------
# ------------------------------------------------
# ------------------------------------------------
if [[ $# -gt 0 ]] ; then
  pipenv run ampy $@
  exit
fi

_put_all_files
